### ISSUE TITLE
NoVideo mod is not supported (Touchscreen?)

### ISSUE THREAD

**Issue by Hazuki-san** [uyitroa/osr2mp4-core#29]
**Steps to reproduce:**
Pick any replay with Touchscreen mod

**What happens:**
`Traceback (most recent call last):
  File "main.py", line 24, in <module>
    main()
  File "main.py", line 15, in main
    osr2mp4.startall()
  File "C:\Users\Hazuki-san\AppData\Local\Programs\Python\Python36\lib\site-packages\autologging.py", line 1039, in autologging_traced_instancemethod_delegator
    return proxy(method, args, keywords)
  File "C:\Users\Hazuki-san\AppData\Local\Programs\Python\Python36\lib\site-packages\autologging.py", line 1196, in __call__
    value = function(*args, **keywords)
  File "E:\GitHub\osr2mp4-core\osr2mp4\osr2mp4.py", line 153, in startall
    self.analyse_replay()
  File "C:\Users\Hazuki-san\AppData\Local\Programs\Python\Python36\lib\site-packages\autologging.py", line 1039, in autologging_traced_instancemethod_delegator
    return proxy(method, args, keywords)
  File "C:\Users\Hazuki-san\AppData\Local\Programs\Python\Python36\lib\site-packages\autologging.py", line 1196, in __call__
    value = function(*args, **keywords)
  File "E:\GitHub\osr2mp4-core\osr2mp4\osr2mp4.py", line 144, in analyse_replay
    self.resultinfo = checkmain(self.beatmap, self.replay_info, self.settings)
  File "E:\GitHub\osr2mp4-core\osr2mp4\CheckSystem\checkmain.py", line 107, in checkmain
    hitobjectchecker = HitObjectChecker(beatmap, settings, replay_info.mod_combination, tests)
  File "E:\GitHub\osr2mp4-core\osr2mp4\CheckSystem\HitObjectChecker.py", line 71, in __init__
    self.mod_multiplier = getmultiplier(mods)
  File "E:\GitHub\osr2mp4-core\osr2mp4\CheckSystem\HitObjectChecker.py", line 40, in getmultiplier
    result *= multiplier[m]
KeyError: <Mod.NoVideo: 4>`

**Did this work on a previous version?**
No

**Additional information:**
-

**Comment by Hazuki-san** [comment]
This can be fixed by adding `Mod.NoVideo: 1` in osr2mp4-core\osr2mp4\CheckSystem\HitObjectChecker.py

**Comment by Hazuki-san** [comment]
#30
