### ISSUE TITLE
Problem when trying to convert a replay

### ISSUE THREAD

**Issue by aWraithToGo** [uyitroa/osr2mp4-core#95]
When I start the process of converting a replay it just gives out this error:

TypeError("object of type 'NoneType' has no len()")object of type 'NoneType' has no len() Traceback (most recent call last):
  File "libs/pythonlib/lib/site-packages/osr2mp4app/run_osu.py", line 92, in <module>
    run()
  File "libs/pythonlib/lib/site-packages/osr2mp4app/run_osu.py", line 50, in run
    converter = Osr2mp4(filedata=config, filesettings=settings, filepp=ppsettings, logtofile=True, logpath=logpath)
  File "C:\Users\Darius\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\autologging.py", line 1041, in autologging_traced_instancemethod_delegator
    return method(*args, **keywords)
  File "C:\Users\Darius\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\osr2mp4.py", line 141, in __init__
    self.replay_event, self.cur_time = setup_replay(replaypath, self.beatmap, reverse=reverse_replay)
  File "C:\Users\Darius\Desktop\osr2mp4\libs\pythonlib\lib\site-packages\osr2mp4\Parser\osrparser.py", line 40, in setup_replay
    for index in range(len(replay_info.play_data)):
TypeError: object of type 'NoneType' has no len()

I'm clueless and really wanna use the converter.

**Comment by uyitroa** [comment]
Is that a standard play? or mania,taiko ctb?

Send the replay and map.
And try another map.

**Comment by aWraithToGo** [comment]
I guess other modes than standard can't be converted yet?
It works when I tried with a standard map (non-convert to different mode,
because that doesn't work either obviously)

Sad though, unless it's planned I will have to record my replays for the
other modes with a recording tool.

Thank you for letting me know though.

Am Mi., 31. März 2021 um 21:06 Uhr schrieb uyitroa ***@***.***
